services:
  - type: web
    name: autosvc
    env: python
    buildCommand: pip install -r requirements.txt && flask db upgrade || echo "Migraciones completadas o no necesarias"
    startCommand: python -m waitress --listen=0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: FLASK_APP
        value: app.py

